[project]
name = "RADDINO_Embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.0"
dependencies = [
    "albumentations>=2.0.3",
    "einops>=0.8.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "lightning==2.4.0",
    "matplotlib>=3.9.4",
    "monai[itk,nibabel]==1.3.2",
    "numpy==1.26.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
    "pydicom>=3.0.1",
    "rich>=13.9.4",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "timm>=1.0.14",
    "torch==2.5.1",
    "torchvision>=0.20.1",
    "transformers>=4.48.2",
    "wandb>=0.19.5",
]


